"""Initial schema with renamed tables

Revision ID: de7bdf19b56d
Revises: 
Create Date: 2026-06-23 11:25:47.425969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de7bdf19b56d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_quality_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_air_quality_stations_city'), 'air_quality_stations', ['city'], unique=False)
    op.create_index(op.f('ix_air_quality_stations_id'), 'air_quality_stations', ['id'], unique=False)
    op.create_index(op.f('ix_air_quality_stations_state'), 'air_quality_stations', ['state'], unique=False)
    op.create_index(op.f('ix_air_quality_stations_station_id'), 'air_quality_stations', ['station_id'], unique=True)
    op.create_table('fire_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('frp', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fire_data_id'), 'fire_data', ['id'], unique=False)
    op.create_index(op.f('ix_fire_data_latitude'), 'fire_data', ['latitude'], unique=False)
    op.create_index(op.f('ix_fire_data_longitude'), 'fire_data', ['longitude'], unique=False)
    op.create_index(op.f('ix_fire_data_timestamp'), 'fire_data', ['timestamp'], unique=False)
    op.create_table('hcho_hotspots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('hcho_mean', sa.Float(), nullable=False),
    sa.Column('hcho_max', sa.Float(), nullable=False),
    sa.Column('point_count', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hcho_hotspots_cluster_id'), 'hcho_hotspots', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_hcho_hotspots_id'), 'hcho_hotspots', ['id'], unique=False)
    op.create_index(op.f('ix_hcho_hotspots_timestamp'), 'hcho_hotspots', ['timestamp'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('TRAINING', 'READY', 'FAILED', 'DEPRECATED', name='modelstatus'), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index(op.f('ix_ml_models_id'), 'ml_models', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('predicted_pm25', sa.Float(), nullable=False),
    sa.Column('predicted_aqi', sa.Float(), nullable=False),
    sa.Column('aqi_category', sa.Enum('GOOD', 'SATISFACTORY', 'MODERATE', 'POOR', 'VERY_POOR', 'SEVERE', name='aqicategory'), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_latitude'), 'predictions', ['latitude'], unique=False)
    op.create_index(op.f('ix_predictions_longitude'), 'predictions', ['longitude'], unique=False)
    op.create_index(op.f('ix_predictions_timestamp'), 'predictions', ['timestamp'], unique=False)
    op.create_table('satellite_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('pollutant', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_data_id'), 'satellite_data', ['id'], unique=False)
    op.create_index(op.f('ix_satellite_data_latitude'), 'satellite_data', ['latitude'], unique=False)
    op.create_index(op.f('ix_satellite_data_longitude'), 'satellite_data', ['longitude'], unique=False)
    op.create_index(op.f('ix_satellite_data_pollutant'), 'satellite_data', ['pollutant'], unique=False)
    op.create_index(op.f('ix_satellite_data_timestamp'), 'satellite_data', ['timestamp'], unique=False)
    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_logs_id'), 'task_logs', ['id'], unique=False)
    op.create_index(op.f('ix_task_logs_task_id'), 'task_logs', ['task_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_data_id'), 'weather_data', ['id'], unique=False)
    op.create_index(op.f('ix_weather_data_latitude'), 'weather_data', ['latitude'], unique=False)
    op.create_index(op.f('ix_weather_data_longitude'), 'weather_data', ['longitude'], unique=False)
    op.create_index(op.f('ix_weather_data_timestamp'), 'weather_data', ['timestamp'], unique=False)
    op.create_table('air_quality_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('no2', sa.Float(), nullable=True),
    sa.Column('so2', sa.Float(), nullable=True),
    sa.Column('co', sa.Float(), nullable=True),
    sa.Column('o3', sa.Float(), nullable=True),
    sa.Column('nh3', sa.Float(), nullable=True),
    sa.Column('aqi', sa.Float(), nullable=True),
    sa.Column('aqi_category', sa.Enum('GOOD', 'SATISFACTORY', 'MODERATE', 'POOR', 'VERY_POOR', 'SEVERE', name='aqicategory'), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['air_quality_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_air_quality_data_id'), 'air_quality_data', ['id'], unique=False)
    op.create_index(op.f('ix_air_quality_data_station_id'), 'air_quality_data', ['station_id'], unique=False)
    op.create_index(op.f('ix_air_quality_data_timestamp'), 'air_quality_data', ['timestamp'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='datasetstatus'), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_index(op.f('ix_datasets_source'), 'datasets', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasets_source'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_air_quality_data_timestamp'), table_name='air_quality_data')
    op.drop_index(op.f('ix_air_quality_data_station_id'), table_name='air_quality_data')
    op.drop_index(op.f('ix_air_quality_data_id'), table_name='air_quality_data')
    op.drop_table('air_quality_data')
    op.drop_index(op.f('ix_weather_data_timestamp'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_longitude'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_latitude'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_id'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_task_logs_task_id'), table_name='task_logs')
    op.drop_index(op.f('ix_task_logs_id'), table_name='task_logs')
    op.drop_table('task_logs')
    op.drop_index(op.f('ix_satellite_data_timestamp'), table_name='satellite_data')
    op.drop_index(op.f('ix_satellite_data_pollutant'), table_name='satellite_data')
    op.drop_index(op.f('ix_satellite_data_longitude'), table_name='satellite_data')
    op.drop_index(op.f('ix_satellite_data_latitude'), table_name='satellite_data')
    op.drop_index(op.f('ix_satellite_data_id'), table_name='satellite_data')
    op.drop_table('satellite_data')
    op.drop_index(op.f('ix_predictions_timestamp'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_longitude'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_latitude'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_ml_models_id'), table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_hcho_hotspots_timestamp'), table_name='hcho_hotspots')
    op.drop_index(op.f('ix_hcho_hotspots_id'), table_name='hcho_hotspots')
    op.drop_index(op.f('ix_hcho_hotspots_cluster_id'), table_name='hcho_hotspots')
    op.drop_table('hcho_hotspots')
    op.drop_index(op.f('ix_fire_data_timestamp'), table_name='fire_data')
    op.drop_index(op.f('ix_fire_data_longitude'), table_name='fire_data')
    op.drop_index(op.f('ix_fire_data_latitude'), table_name='fire_data')
    op.drop_index(op.f('ix_fire_data_id'), table_name='fire_data')
    op.drop_table('fire_data')
    op.drop_index(op.f('ix_air_quality_stations_station_id'), table_name='air_quality_stations')
    op.drop_index(op.f('ix_air_quality_stations_state'), table_name='air_quality_stations')
    op.drop_index(op.f('ix_air_quality_stations_id'), table_name='air_quality_stations')
    op.drop_index(op.f('ix_air_quality_stations_city'), table_name='air_quality_stations')
    op.drop_table('air_quality_stations')
    # ### end Alembic commands ###
